services:
  postgres:
    image: postgres:16.5-alpine
    container_name: board-api-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: board-api-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d
volumes:
  postgres-data: